# Generated by Django 4.2.3 on 2023-07-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfapp', '0003_registered_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
